// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    public class SteamVR_Input_ActionSet_ui_input : Valve.VR.SteamVR_ActionSet
    {
        
        public SteamVR_Input_ActionSet_ui_input_In inActions;
        
        public SteamVR_Input_ActionSet_ui_input_Out outActions;
    }
}
