// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    public class SteamVR_Input_ActionSet_ui_input_In : Valve.VR.SteamVR_Action_List
    {
        
        public Valve.VR.SteamVR_Action_Vector2 Navigate;
        
        public Valve.VR.SteamVR_Action_Boolean NavigateClick;
        
        public Valve.VR.SteamVR_Action_Boolean Confirm;
        
        public Valve.VR.SteamVR_Action_Boolean Show;
    }
}
